config/routes.rb
Rails.application.routes.draw do
	# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'sentencer#annotation'

  devise_for :users
  get '/users/:email' => 'users#show', :constraints => { :email => /.+@.+\..*/ }, as: 'user'

	resources :configs

  get  '/annotation' => 'sentencer#annotation'
  post '/annotation' => 'sentencer#annotation'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/config.rb
class Config < ApplicationRecord
	belongs_to :user

	include FriendlyId
	friendly_id :name

	validates :name, presence: true, uniqueness: true, length:{minimum:5, maximum:32}
	validates_format_of :name, :with => /\A[a-z0-9]+\z/i

	validates :body, presence: true
	validate :body_must_be_json

	private

	def body_must_be_json
		JSON.parse(body)
	rescue => e
		errors.add(:base, "Body is not a valid JSON object")
		errors.add(:base, e.message)
	end

end

app/models/user.rb
class User < ApplicationRecord
	has_many :configs, dependent: :destroy

	include FriendlyId
	friendly_id :email

	validates :email, uniqueness: true

	# Include default devise modules. Others available are:
	# :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
	devise :database_authenticatable, :registerable, :confirmable, 
				 :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/configs_controller.rb
class ConfigsController < ApplicationController
	before_action :set_config, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!, except: [:index, :show]

	# GET /configs
	# GET /configs.json
	def index
		@configs = Config.all
	end

	# GET /configs/1
	# GET /configs/1.json
	def show
	end

	# GET /configs/new
	def new
		@config = Config.new
	end

	# GET /configs/1/edit
	def edit
	end

	# POST /configs
	# POST /configs.json
	def create
    @config = current_user.configs.new(config_params)

		respond_to do |format|
			if @config.save
				format.html { redirect_to @config, notice: 'Config was successfully created.' }
				format.json { render :show, status: :created, location: @config }
			else
				format.html { render :new }
				format.json { render json: @config.errors, status: :unprocessable_entity }
			end
		end
	end

	# PATCH/PUT /configs/1
	# PATCH/PUT /configs/1.json
	def update
		respond_to do |format|
			if @config.update(config_params)
				format.html { redirect_to @config, notice: 'Config was successfully updated.' }
				format.json { render :show, status: :ok, location: @config }
			else
				format.html { render :edit }
				format.json { render json: @config.errors, status: :unprocessable_entity }
			end
		end
	end

	# DELETE /configs/1
	# DELETE /configs/1.json
	def destroy
		@config.destroy
		respond_to do |format|
			format.html { redirect_to configs_url, notice: 'Config was successfully destroyed.' }
			format.json { head :no_content }
		end
	end

	private
		# Use callbacks to share common setup or constraints between actions.
		def set_config
			@config = Config.friendly.find(params[:id])
		end

		# Only allow a list of trusted parameters through.
		def config_params
      params.require(:config).permit(:name, :description, :body, :is_public)
		end
end

app/controllers/sentencer_controller.rb
class SentencerController < ApplicationController
	skip_before_action :verify_authenticity_token

	def annotation
		begin
			text = if params[:text].present?
				params[:text]
			else
				request.body.read.dup.force_encoding('UTF-8')
			end

			config_name = if params[:config].present?
				params[:config]
			else
				'PubMed'
			end

			config = begin
				r = Config.friendly.find(config_name)
				config = JSON.parse r.body, symbolize_names: true
			rescue
				{}
			end

			@result = if text.present?
				annotator = TextSentencer.new(TextSentencer::DEFAULT_RULES)
				annotator.annotate(text)
			else
				{}
			end

			respond_to do |format|
				format.html {
					@configs = Config.all.pluck(:name)
				}
				format.json {
					raise ArgumentError, "no text was supplied." unless text.present?
					render json:@result
				}
			end
		rescue ArgumentError => e
			respond_to do |format|
				format.html
				format.any {render json: {message:e.message}, status: :bad_request}
			end
		rescue => e
			respond_to do |format|
				format.html
				format.any {render json: {message:e.message}, status: :internal_server_error}
			end
		end
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def show
		@user = User.friendly.find(params[:email])
		@configs = Config.where(user_id: @user.id)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/configs_helper.rb
module ConfigsHelper
end

app/helpers/users_helper.rb
module UsersHelper
	def user(user)
		link_to user.email, user_path(user)
	end
end

app/views/configs/_config.html.erb
<tr>
	<td><%= link_to(config.name, config, class: 'cell-link') %></td>
	<td><%= link_to(strip_tags(config.description), config, class: 'cell-link') %></td>
	<td><%= link_to(config.user.email, config.user, class: 'cell-link') %></td>
</tr>

app/views/configs/_configs.html.erb
<div class='configs-list'>
	<table>
		<colgroup>
			<col class="col-config-name">
			<col class="col-config-desc">
			<col class="col-config-user">
		</colgroup>
		<tbody>
			<%= render partial: 'configs/config', collection: configs %>
		<tdoby>
	</table>
</div>

app/views/configs/_form.html.erb
<%= form_for(@config) do |f| %>
  <% if @config.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@config.errors.count, "error") %> prohibited this config from being saved:</h2>

      <ul>
      <% @config.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<table class='virtical wide'>
  <tr>
    <th><%= f.label :name %></th>
    <td><%= f.text_field :name %></td>
  </tr>
  <tr>
    <th><%= f.label :description %></th>
    <td><%= f.text_area :description %></td>
  </tr>
  <tr>
    <th><%= f.label :body %></th>
    <td><%= f.text_area :body, class: "json" %></td>
    <!-- <td><div id='config_body'></div></td> -->
  </tr>
  <tr>
    <th><%= f.label :is_public %></th>
    <td><%= f.check_box :is_public %></td>
  </tr>
</table>
<div class="actions">
  <%= f.submit %>
</div>
<% end %>

app/views/configs/edit.html.erb
<h1>Editing Config</h1>

<%= render 'form' %>

<%= link_to 'Back', @config, class: 'button' %>
<%= link_to 'List', configs_path, class: 'button' %>

app/views/configs/index.html.erb
<h1>
Configs
<%=
	if current_user
		link_to 'Create', new_config_path, class: 'button'
	else
		link_to 'Login for creation', new_user_session_path, class: 'button'
	end
%>
</h1>

<%= render partial: 'configs', locals: {configs:@configs} %>

app/views/configs/new.html.erb
<h1>New Config</h1>

<%= render 'form' %>

<%= link_to 'Back to list', configs_path, class: 'button' %>

app/views/configs/show.html.erb
<div>
<%= link_to 'back to list', configs_path, class: 'button' %>
</div>

<h1>
<span class='prefix'>Config</span>
<%= @config.name %>
<% if @config.is_public %>
<span class='tag'><%= fa_icon 'flag', title: 'publicly listed' %></span>
<% end %>
<%= link_to 'Edit', edit_config_path(@config), class: 'button' if @config.user == current_user %>
</h1>
<div>
<%=
	if @config.description
		@config.description
	else
		'description empty'
	end
%>
</div>

<table class="virtical wide">
<tr>
	<th>Creator</th>
	<td><%= user(@config.user) %></td>
</tr>

<tr>
  <th>Body</th>
  <td>
<pre><%= JSON.pretty_generate(JSON.parse @config.body) %></pre>
  </td>
</tr>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>TextSentencer</title>
		<meta name="viewport" content="width=device-width,initial-scale=1">
		<%= csrf_meta_tags %>
		<%= csp_meta_tag %>

		<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
		<%= yield :css -%>
		<%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
		<%= yield :javascript -%>
</head>

	<body>
		<div id='canvas'>

		<div class="frame">
		<div class="title">
			<%= link_to 'TextSentencer', root_path, id: 'logo' %>
			<ul class="main-nav">
				<li><%= link_to 'Configs', configs_path %></li>
				<li><a href="https://github.com/jdkim/text_sentencer">GitHub</a></li>
			</ul>
		</div>

		<div class="ribbon">
			<div class="notice"><%= notice %></div>
			<div id="account" class="menu">
				<ul>
					<li><%= render 'devise/menu/registration_items' %></li>
					<li><%= render 'devise/menu/login_items' %></li>
				</ul>
			</div>
		</div>
		</div>
		<div class="path">
			<div class="content">
				<%= yield :path -%>
			</div>
		</div>

		<div class="content">
			<%= yield %>
		</div>
	</body>
</html>

app/views/sentencer/_textae_css_js.html.erb
<%
	content_for :css do
		stylesheet_link_tag "http://textae.pubannotation.org/lib/css/textae.min.css"
	end

	content_for :javascript do
		javascript_include_tag "http://textae.pubannotation.org/lib/textae.min.js"
	end
-%>

app/views/sentencer/annotation.html.erb
<h1>Demo</h1>

<h2>Text for test</h2>
<%= form_tag({}, {id: 'demo_form', method: :get}) do -%>
<%= text_field_tag :config, params[:config], hidden:true %>
<%= text_area_tag :text, params[:text] || "This is a sample sentence. This is another.", required: true, rows: 4 %>
<br/>

<%= submit_tag 'Submit', class: :button %>
<%= button_tag 'Reset', type: :reset, id: :reset, class: :button %>
<% end %>
<br/>

<fieldset style="background-color: #FBFBF9">
<legend>
	Choose a preset configuration:
	<%= select_tag(:config_name, options_for_select(@configs, params[:config])) -%>
</legend>

<h3>REST service URL</h3>

<table>
<tr>
<td><div id="rest_url"></div></td>
<td>
<button class="btn" id="clip-btn-url" data-clipboard-action="copy" data-clipboard-target="#rest_url">
	<%= image_tag 'clippy.svg', class: 'clippy', width: 13, alt: 'Copy to clipboard' %>
</button>
</td>
</tr>
</table>

<h3>Example cURL commands</h3>

<table>
<tr>
<th>GET</th>
<td><div id="curl_command_get"></div></td>
<td>
	<button class="btn" id="clip-btn-get" data-clipboard-action="copy" data-clipboard-target="#curl_command_get">
		<%= image_tag 'clippy.svg', class: 'clippy', width: 13, alt: 'Copy to clipboard' %>
	</button>
</td>
</tr>

<tr>
<th>POST1</th>
<td><div id="curl_command_post1"></div></td>
<td>
	<button class="btn" id="clip-btn-post1" data-clipboard-action="copy" data-clipboard-target="#curl_command_post1">
		<%= image_tag 'clippy.svg', class: 'clippy', width: 13, alt: 'Copy to clipboard' %>
	</button>
</td>
</tr>
<tr>
<th>POST2</th>
<td><div id="curl_command_post2"></div></td>
<td>
	<button class="btn" id="clip-btn-post2" data-clipboard-action="copy" data-clipboard-target="#curl_command_post2">
		<%= image_tag 'clippy.svg', class: 'clippy', width: 13, alt: 'Copy to clipboard' %>
	</button>
</td>
</tr>
<tr>
<th>POST3</th>
<td><div id="curl_command_post3"></div></td>
<td>
	<button class="btn" id="clip-btn-post3" data-clipboard-action="copy" data-clipboard-target="#curl_command_post3">
		<%= image_tag 'clippy.svg', class: 'clippy', width: 13, alt: 'Copy to clipboard' %>
	</button>
</td>
</tr>

</table>

</fieldset>

<% unless @result.nil? || @result.empty? %>
	<h2>Result</h2>

	<h3>In <%= link_to 'TextAE', 'http://textae.pubannotation.org' %></h3>
	<%= render :partial => 'textae_css_js'-%>
	<div class="textae-editor"><%= @result.to_json %></div>

	<h3>In JSON (the <%= link_to 'PubAnnotation scheme', 'http://www.pubannotation.org/docs/annotation-format/' %>)</h3>
	<pre style="border: 1px solid #000; padding: 5px; background-color: #FAFAFA"><%= JSON.pretty_generate @result %></pre>
<% end %>

<script type="text/javascript">
	$(function() {
		set_url();
		var clipboard_url   = new Clipboard('#clip-btn-url');
		var clipboard_get   = new Clipboard('#clip-btn-get');
		var clipboard_post1 = new Clipboard('#clip-btn-post1');
		var clipboard_post2 = new Clipboard('#clip-btn-post2');
		var clipboard_post3 = new Clipboard('#clip-btn-post3');
	});

	$('#config_name').on('change', function() {
		$('#config').val($(this).val());
		set_url();
	});

	var text_last_value = '';
	$('#text').on('change keyup paste mouseup', function() {
		if ($(this).val() != text_last_value) {
			text_last_value = $(this).val();
			set_url();
		}
	});

	$('#demo_form').on('reset', function() {
		setTimeout(function() {
			set_url();
		});
	});

	function set_url() {
		var url = '<%= root_url %>annotation.json'

		var config = $('#config').val();
		if (config) {url += '?config=' + config}
		$('#rest_url').text(url);

		var text = $('#text').val();
		if (text == "") {text = "input text"}

		var command_get = 'curl -G --data-urlencode text="' + text + '" "' + url + '"'
		var command_post1 = 'curl -F text="' + text + '" "' + url + '"'
		var command_post2 = 'curl -H "content-type:application/json" -d \'{"text":"' + text + '"}\' "' + url + '"'
		var command_post3 = 'curl -H "content-type:text/plain" -d "' + text + '" "' + url + '"'

		$('#curl_command_get').text(command_get);
		$('#curl_command_post1').text(command_post1);
		$('#curl_command_post2').text(command_post2);
		$('#curl_command_post3').text(command_post3);
	}
</script>

app/views/users/show.html.erb
<section>
	<h1>
		<span class='prefix'>User</span>
		<%= @user.email %>
		<%= link_to 'Edit', edit_user_registration_path, :class => :button if @user == current_user %>
	</h1>
	
	<% if @user == current_user %>
		<table class='virtical'>
			<tr>
				<th>E-mail</th>
				<td><%= @user.email -%></td>
			</tr>
		</table>
	<% end %>

	<section>
		<h2>
			Configurations
			<%= link_to 'Create', new_config_path, class: 'button' %>
		</h2>

		<%= render partial: 'configs/configs', locals: {configs:@configs} %>

	</section>

</section>